apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag2-apr30-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag2-apr30-1:439c72301b9e58a87973d5ccb0b9e5035219bd14@sha256:c542d436be1733513c2c1510943e4962963ae49704f636168acb9b2bb8063b91 # use pre-built to bootstrap
          name: app-inference
